// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgGMyMIHnuIx8FStb4ulzjpVkKNPs8BYw',
    appId: '1:478731322934:android:6a1633a20f763043d3fa97',
    messagingSenderId: '478731322934',
    projectId: 'smart-pet-collar-4am',
    databaseURL: 'https://smart-pet-collar-4am-default-rtdb.firebaseio.com',
    storageBucket: 'smart-pet-collar-4am.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrXaycrusdbgYOnWzRf3t-hfrXjtwqV1g',
    appId: '1:478731322934:ios:0cf7b8bdbb65e328d3fa97',
    messagingSenderId: '478731322934',
    projectId: 'smart-pet-collar-4am',
    databaseURL: 'https://smart-pet-collar-4am-default-rtdb.firebaseio.com',
    storageBucket: 'smart-pet-collar-4am.appspot.com',
    iosClientId: '478731322934-r7hqau2tolhl1lql7boa2aqbvsokplnt.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartPetCollar',
  );
}
